COMPANY_CATALOG = [
    # Existing companies
    {
        "name": "Glean",
        "ats_type": "greenhouse",
        "board_token": "gleanwork",
        "career_url": "https://job-boards.greenhouse.io/gleanwork",
        "enabled": True,
    },
    {
        "name": "Gushwork",
        "ats_type": "lever",
        "board_token": "gushwork",
        "career_url": "https://jobs.lever.co/gushwork",
        "enabled": True,
    },
    {
        "name": "PostHog",
        "ats_type": "ashby",
        "board_token": "posthog",
        "career_url": "https://jobs.ashbyhq.com/posthog",
        "enabled": True,
    },
    {
        "name": "Hevo Data",
        "ats_type": "lever",
        "board_token": "hevodata",
        "career_url": "https://jobs.lever.co/hevodata",
        "enabled": True,
    },
    {
        "name": "Acceldata",
        "ats_type": "lever",
        "board_token": "acceldata",
        "career_url": "https://jobs.lever.co/acceldata",
        "enabled": True,
    },
    {
        "name": "Neuron7",
        "ats_type": "lever",
        "board_token": "neuron7",
        "career_url": "https://jobs.lever.co/neuron7",
        "enabled": True,
    },
    {
        "name": "100MS",
        "ats_type": "lever",
        "board_token": "100ms",
        "career_url": "https://jobs.lever.co/100ms",
        "enabled": True,
    },
    {
        "name": "Bazaarvoice",
        "ats_type": "lever",
        "board_token": "bazaarvoice",
        "career_url": "https://jobs.lever.co/bazaarvoice",
        "enabled": True,
    },

    # More India / Bangalore-heavy tech companies
    {
        "name": "Razorpay",
        "ats_type": "greenhouse",
        "board_token": "razorpaysoftwareprivatelimited",
        "career_url": "https://job-boards.greenhouse.io/razorpaysoftwareprivatelimited",
        "enabled": True,
    },
    {
        "name": "BrowserStack",
        "ats_type": "greenhouse",
        "board_token": "browserstack",
        "career_url": "https://job-boards.greenhouse.io/browserstack",
        "enabled": True,
    },
    {
        "name": "Postman",
        "ats_type": "greenhouse",
        "board_token": "postman",
        "career_url": "https://job-boards.greenhouse.io/postman",
        "enabled": True,
    },
    {
        "name": "Freshworks",
        "ats_type": "greenhouse",
        "board_token": "freshworks",
        "career_url": "https://job-boards.greenhouse.io/freshworks",
        "enabled": True,
    },
    {
        "name": "Chargebee",
        "ats_type": "greenhouse",
        "board_token": "chargebee",
        "career_url": "https://job-boards.greenhouse.io/chargebee",
        "enabled": True,
    },
    {
        "name": "MoEngage",
        "ats_type": "greenhouse",
        "board_token": "moengage",
        "career_url": "https://job-boards.greenhouse.io/moengage",
        "enabled": True,
    },
    {
        "name": "CleverTap",
        "ats_type": "greenhouse",
        "board_token": "clevertap",
        "career_url": "https://job-boards.greenhouse.io/clevertap",
        "enabled": True,
    },
    {
        "name": "Darwinbox",
        "ats_type": "greenhouse",
        "board_token": "darwinbox",
        "career_url": "https://job-boards.greenhouse.io/darwinbox",
        "enabled": True,
    },
    {
        "name": "Innovaccer",
        "ats_type": "greenhouse",
        "board_token": "innovaccer",
        "career_url": "https://job-boards.greenhouse.io/innovaccer",
        "enabled": True,
    },
    {
        "name": "Fractal Analytics",
        "ats_type": "greenhouse",
        "board_token": "fractalanalytics",
        "career_url": "https://job-boards.greenhouse.io/fractalanalytics",
        "enabled": True,
    },
    {
        "name": "Sigmoid",
        "ats_type": "greenhouse",
        "board_token": "sigmoid",
        "career_url": "https://job-boards.greenhouse.io/sigmoid",
        "enabled": True,
    },
    {
        "name": "CRED",
        "ats_type": "lever",
        "board_token": "cred",
        "career_url": "https://jobs.lever.co/cred",
        "enabled": True,
    },
    {
        "name": "Groww",
        "ats_type": "lever",
        "board_token": "groww",
        "career_url": "https://jobs.lever.co/groww",
        "enabled": True,
    },
    {
        "name": "Zepto",
        "ats_type": "lever",
        "board_token": "zeptonow",
        "career_url": "https://jobs.lever.co/zeptonow",
        "enabled": True,
    },
    {
        "name": "Meesho",
        "ats_type": "lever",
        "board_token": "meesho",
        "career_url": "https://jobs.lever.co/meesho",
        "enabled": True,
    },
    {
        "name": "Urban Company",
        "ats_type": "lever",
        "board_token": "urbancompany",
        "career_url": "https://jobs.lever.co/urbancompany",
        "enabled": True,
    },
    {
        "name": "Sarvam AI",
        "ats_type": "ashby",
        "board_token": "sarvam",
        "career_url": "https://jobs.ashbyhq.com/sarvam",
        "enabled": True,
    },
]
